---
title: "Portland"
author: "Luke Kolar"
date: "2024-04-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

```{r}
options(java.parameters = "-Xmx4G") # Crucial for walkshed calculation

library(r5r)
library(geobr)
library(sf)
library(ggplot2)
library(here)
library(osmextract)
library(data.table)
library(magrittr)
library(here)
library(rgdal)
library(mapview)
library(janitor)
library(readxl)
library(ohsome)
library(tabulizer)
library(geojsonio)
library(tinytiger)
library(corrplot)
library(huxtable)
library(readxl)
library(tinytiger)
library(censable)
library(geomander)
library(ggnewscale)
library(stargazer)
library(tidycensus)

library(tidyverse)

census_api_key((read_xlsx(paste0(getwd(), "/data/api_keys.xlsx")) %>% 
                  filter(type == "tidycensus"))$key) # Enter your `tidycensus` API key

```


```{r}
### DATA ###

PDX_all <- readRDS(paste0(getwd(), "/data/portland/PDX_all.rds"))

PDX_protected_lanes <- readRDS(paste0(getwd(), "/data/portland/PDX_protected_lanes.rds"))

PDX_walksheds <- readRDS(paste0(getwd(), "/data/portland/PDX_walksheds.rds"))

PDX_roads <- readRDS(paste0(getwd(), "/data/portland/PDX_roads.rds"))

PDX_gent_index_2016 <- readRDS("data/portland/PDX_gent_index_2016.rds")

```

```{r}
### MODELS ###

mod1 <- lm(wheeler_change ~ gent_area + pre_gent_area + 
                    bgp_perc_auto*bgp_median_age + 
                    pop_density_2010, 
   data = PDX_all %>% mutate(pop_density_2010 = pop_density_2010/1000))

mod2 <- lm(wheeler_change ~ gent_area + pre_gent_area + 
                    bgp_perc_auto*bgp_median_age + 
                    pop_density_2010 + 
                    t1_paint_all + t1_prtct_all + 
                    gent_area:t1_paint_all + pre_gent_area:t1_paint_all + 
                    gent_area:t1_prtct_all + pre_gent_area:t1_prtct_all + 
                    bgp_perc_auto:bgp_median_age:t1_paint_all + 
                    bgp_perc_auto:bgp_median_age:t1_prtct_all, 
   data = PDX_all %>% mutate(pop_density_2010 = pop_density_2010/1000))

mod3 <- lm(wheeler_change ~ gent_area + pre_gent_area + 
                    bgp_perc_auto*bgp_median_age + 
                    pop_density_2010 + 
                    t1_paint_all + t1_prtct_type1 + t1_prtct_type2 + 
                    gent_area:t1_paint_all + pre_gent_area:t1_paint_all + 
                    gent_area:t1_prtct_type1 + pre_gent_area:t1_prtct_type1 + 
                    gent_area:t1_prtct_type2 + pre_gent_area:t1_prtct_type2 + 
                    bgp_perc_auto:bgp_median_age:t1_paint_all + 
                    bgp_perc_auto:bgp_median_age:t1_prtct_type1 + 
                    bgp_perc_auto:bgp_median_age:t1_prtct_type2, 
   data = PDX_all %>% mutate(pop_density_2010 = pop_density_2010/1000))

mod4 <- lm(wheeler_change ~ gent_area + pre_gent_area + 
                    bgp_perc_auto*bgp_median_age + 
                    pop_density_2010 + 
                    t1_paint_all + t1_prtct_type1_2019 + t1_prtct_type2_2019 + 
                    t1_prtct_type1_2020 + t1_prtct_type2_2020 + 
                    gent_area:t1_paint_all + pre_gent_area:t1_paint_all + 
                    gent_area:t1_prtct_type1_2019 + pre_gent_area:t1_prtct_type1_2019 + 
                    gent_area:t1_prtct_type2_2019 + pre_gent_area:t1_prtct_type2_2019 + 
                    gent_area:t1_prtct_type1_2020 + pre_gent_area:t1_prtct_type1_2020 + 
                    gent_area:t1_prtct_type2_2020 + pre_gent_area:t1_prtct_type2_2020 + 
                    bgp_perc_auto:bgp_median_age:t1_paint_all + 
                    bgp_perc_auto:bgp_median_age:t1_prtct_type1_2019 + 
                    bgp_perc_auto:bgp_median_age:t1_prtct_type2_2019 +
                    bgp_perc_auto:bgp_median_age:t1_prtct_type1_2020 + 
                    bgp_perc_auto:bgp_median_age:t1_prtct_type2_2020, 
   data = PDX_all %>% mutate(pop_density_2010 = pop_density_2010/1000))

# stargazer(mod1, mod2, mod3, mod4, title="Regression Results",
#           dep.var.labels=c("Wheeler vote share change"),
#           column.labels = c("Model 1", "Model 2", "Model 3", "Model 4"))

# anova(mod1, mod2)[1:6]
# anova(mod1, mod3)[1:6]
# anova(mod1, mod4)[1:6]

mod5 <- lm(wheeler_change ~ gent_area + pre_gent_area + 
                    bgp_perc_auto*bgp_median_age + 
                    pop_density_2010 + 
                    t1_paint_all + t2_prtct_all + 
                    gent_area:t2_prtct_all + pre_gent_area:t2_prtct_all + 
                    bgp_perc_auto:bgp_median_age:t2_prtct_all, 
   data = PDX_all %>% mutate(pop_density_2010 = pop_density_2010/1000))

mod6 <- lm(wheeler_change ~ gent_area + pre_gent_area + 
                    bgp_perc_auto*bgp_median_age + 
                    pop_density_2010 + 
                    t1_paint_all + 
                    t2_prtct_type1 + t2_prtct_type2 + 
                    gent_area:t2_prtct_type1 + pre_gent_area:t2_prtct_type1 + 
                    gent_area:t2_prtct_type2 + pre_gent_area:t2_prtct_type2 + 
                    bgp_perc_auto:bgp_median_age:t2_prtct_type1 + 
                    bgp_perc_auto:bgp_median_age:t2_prtct_type2, 
   data = PDX_all %>% mutate(pop_density_2010 = pop_density_2010/1000))

mod7 <- lm(wheeler_change ~ gent_area + pre_gent_area + 
                    bgp_perc_auto*bgp_median_age + 
                    pop_density_2010 + 
                    t1_paint_all + 
                    t2_prtct_type1_2019 + t2_prtct_type2_2019 + 
                    t2_prtct_type1_2020 + t2_prtct_type2_2020 + 
                    gent_area:t2_prtct_type1_2019 + pre_gent_area:t2_prtct_type1_2019 + 
                    gent_area:t2_prtct_type2_2019 + pre_gent_area:t2_prtct_type2_2019 + 
                    gent_area:t2_prtct_type1_2020 + pre_gent_area:t2_prtct_type1_2020 + 
                    gent_area:t2_prtct_type2_2020 + pre_gent_area:t2_prtct_type2_2020 +
                    bgp_perc_auto:bgp_median_age:t2_prtct_type1_2019 + 
                    bgp_perc_auto:bgp_median_age:t2_prtct_type2_2019 + 
                    bgp_perc_auto:bgp_median_age:t2_prtct_type1_2020 + 
                    bgp_perc_auto:bgp_median_age:t2_prtct_type2_2020, 
   data = PDX_all %>% mutate(pop_density_2010 = pop_density_2010/1000))

# stargazer(mod1, mod5, mod6, mod7, title="Regression Results",
#           dep.var.labels=c("Wheeler vote share change"),
#           column.labels = c("Model 1", "Model 5", "Model 6", "Model 7"))

# anova(mod1, mod5)[1:6]
# anova(mod1, mod6)[1:6]
# anova(mod1, mod7)[1:6]

```

```{r}
### FIGURES: MAPS ###

pdx_fig1 <- PDX_all %>% st_as_sf() %>% ggplot() + 
  geom_sf(aes(fill = wheeler_change)) + theme_void() + 
  scale_fill_continuous(low = "red", high = "white") + 
  labs(fill = expression(paste(Delta, " Wheeler    "))) + 
  theme(plot.background = element_rect(fill = "white", color = NA))

pdx_fig2 <- PDX_all %>% st_as_sf() %>% ggplot() + 
  geom_sf(fill = "aliceblue") + theme_void() + 
  geom_sf(data = rbind(PDX_roads %>% mutate(type = "Roads", width = "0.1"),
                       PDX_protected_lanes %>% 
                         summarize(geometry = st_union(geometry)) %>% 
                         mutate(type = "Protected    \nlanes", 
                                width = "1")) %>% st_as_sf(),
          aes(color = type, lwd = width), alpha = 1) + 
  scale_color_manual(values = c("red", "blue"), name = "") + 
  scale_discrete_manual("linewidth", values = c(0.0375, 1), guide = "none") + 
  theme(plot.background = element_rect(fill = "white", color = NA))

pdx_fig3 <- PDX_all %>% st_as_sf() %>% ggplot() + 
  geom_sf(fill = "aliceblue") + theme_void() + 
  geom_sf(data = PDX_walksheds %>% 
            select(walk_15) %>% 
            st_as_sf() %>% 
            st_make_valid() %>% 
            summarize(walk_15 = st_union(walk_15)) %>% 
            mutate(type = "15-min.\nwalkshed    "), 
          aes(fill = type), alpha = 0.75) + 
  scale_fill_manual(values = "red", name = "") + 
  theme(plot.background = element_rect(fill = "white", color = NA))

pdx_fig9a <- pdx_fig3

pdx_fig9b <- ggplot() + geom_sf(data = PDX_all %>% st_as_sf(), 
                                aes(fill = t1_prtct_all)) + 
  theme_void() + 
  scale_fill_distiller(name = "T1 (all)      ", direction = 1, palette = "Oranges") + 
  theme(plot.background = element_rect(fill = "white", color = NA))

pdx_fig10a <- ggplot() + geom_sf(data = PDX_all %>% st_as_sf(), 
                                 aes(fill = as.numeric(area_miles))) + 
  theme_void() + 
  scale_fill_distiller(name = "Sq. miles    ", direction = 1) + 
  new_scale("fill") + 
  geom_sf(data = PDX_walksheds %>% 
            select(walk_15) %>% 
            st_as_sf() %>% 
            st_make_valid() %>% 
            summarize(walk_15 = st_union(walk_15)) %>% 
            mutate(type = "15-min.\nwalkshed    "), 
          aes(fill = type), alpha = 0.75) + 
  scale_fill_manual(values = "red", name = "") + 
  theme(plot.background = element_rect(fill = "white", color = NA))

pdx_fig10b <- ggplot() + geom_sf(data = PDX_all %>% st_as_sf(), 
                                 aes(fill = t2_prtct_all)) + 
  theme_void() + 
  scale_fill_distiller(name = "T2 (all)      ", direction = 1, palette = "Oranges") + 
  theme(plot.background = element_rect(fill = "white", color = NA))

# ggsave("figures/pdx/pdx_fig1.png", pdx_fig1, width = 4, height = 3, dpi = 200)
# ggsave("figures/pdx/pdx_fig2.png", pdx_fig2, width = 4, height = 3, dpi = 200)
# ggsave("figures/pdx/pdx_fig3.png", pdx_fig3, width = 4, height = 3, dpi = 200)
# ggsave("figures/pdx/pdx_fig9a.png", pdx_fig9a, width = 4, height = 3, dpi = 200)
# ggsave("figures/pdx/pdx_fig9b.png", pdx_fig9b, width = 4, height = 3, dpi = 200)
# ggsave("figures/pdx/pdx_fig10a.png", pdx_fig10a, width = 4, height = 3, dpi = 200)
# ggsave("figures/pdx/pdx_fig10b.png", pdx_fig10b, width = 4, height = 3, dpi = 200)


```

```{r}
### FIGURES: HISTOGRAMS ###

h1 <- PDX_all %>% 
  ggplot(aes(x = wheeler_change)) + geom_histogram(fill = "blue") + theme_minimal() + 
  labs(x = NULL, y = NULL) + 
  theme(plot.background = element_rect(fill = "white", color = NA))

h2 <- PDX_all %>% 
  ggplot(aes(x = t1_prtct_all)) + geom_histogram(fill = "blue") + theme_minimal() + 
  labs(x = NULL, y = NULL) + 
  theme(plot.background = element_rect(fill = "white", color = NA))

h3 <- PDX_all %>% 
  ggplot(aes(x = t2_prtct_all)) + geom_histogram(fill = "blue") + theme_minimal() + 
  labs(x = NULL, y = NULL) + 
  theme(plot.background = element_rect(fill = "white", color = NA))

h4 <- PDX_all %>% 
  ggplot(aes(x = pre_gent_area)) + geom_histogram(fill = "blue") + theme_minimal() + 
  labs(x = NULL, y = NULL) + 
  theme(plot.background = element_rect(fill = "white", color = NA))

h5 <- PDX_all %>% 
  ggplot(aes(x = gent_area)) + geom_histogram(fill = "blue") + theme_minimal() + 
  labs(x = NULL, y = NULL) + 
  theme(plot.background = element_rect(fill = "white", color = NA))

h6 <- PDX_all %>% 
  ggplot(aes(x = bgp_perc_auto)) + geom_histogram(fill = "blue") + theme_minimal() + 
  labs(x = NULL, y = NULL) + 
  theme(plot.background = element_rect(fill = "white", color = NA))

h7 <- PDX_all %>% 
  ggplot(aes(x = bgp_median_age)) + geom_histogram(fill = "blue") + theme_minimal() + 
  labs(x = NULL, y = NULL) + 
  theme(plot.background = element_rect(fill = "white", color = NA))

h8 <- PDX_all %>% 
  ggplot(aes(x = as.numeric(pop_density_2010))) + geom_histogram(fill = "blue") + theme_minimal() + 
  labs(x = NULL, y = NULL) + 
  theme(plot.background = element_rect(fill = "white", color = NA))

# ggsave("figures/pdx/hist/pdx_h1.png", h1, width = 4, height = 3, dpi = 100)
# ggsave("figures/pdx/hist/pdx_h2.png", h2, width = 4, height = 3, dpi = 100)
# ggsave("figures/pdx/hist/pdx_h3.png", h3, width = 4, height = 3, dpi = 100)
# ggsave("figures/pdx/hist/pdx_h4.png", h4, width = 4, height = 3, dpi = 100)
# ggsave("figures/pdx/hist/pdx_h5.png", h5, width = 4, height = 3, dpi = 100)
# ggsave("figures/pdx/hist/pdx_h6.png", h6, width = 4, height = 3, dpi = 100)
# ggsave("figures/pdx/hist/pdx_h7.png", h7, width = 4, height = 3, dpi = 100)
# ggsave("figures/pdx/hist/pdx_h8.png", h8, width = 4, height = 3, dpi = 100)
```
