---
title: "Portland"
author: "Luke Kolar"
date: "2024-04-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

```{r}
options(java.parameters = "-Xmx4G") # Crucial for walkshed calculation

library(r5r)
library(geobr)
library(sf)
library(ggplot2)
library(here)
library(osmextract)
library(data.table)
library(magrittr)
library(here)
library(rgdal)
library(mapview)
library(janitor)
library(readxl)
library(ohsome)
library(tabulizer)
library(geojsonio)
library(tinytiger)
library(corrplot)
library(huxtable)
library(readxl)
library(tinytiger)
library(censable)
library(geomander)
library(ggnewscale)
library(stargazer)
library(raster)
library(viridis)
library(tidycensus)

library(tidyverse)

census_api_key((read_xlsx(paste0(getwd(), "/data/api_keys.xlsx")) %>% 
                  filter(type == "tidycensus"))$key) # Enter your `tidycensus` API key

```


```{r}
### DATA ###

##########FIX VARS
########## CONVERT TO TIBBLE

SEA_lanes_final <- readRDS("data/seattle/SEA_lanes_final.rds") 

### REMOVE TRANSFORM
SEA_walksheds <- readRDS("data/seattle/SEA_walksheds.rds")

SEA_boundary <- readRDS("data/seattle/SEA_boundary.rds")

SEA_elections_odd <- readRDS("data/seattle/SEA_elections_odd.rds")    # local races
SEA_elections_even <- readRDS("data/seattle/SEA_elections_even.rds")  # federal races

```

```{r}
### MODELS ###

mod1a <- SEA_elections_odd %>% 
  mutate(popw_median_inc_2010_1k = popw_median_inc_2010/1000, 
         perc_white_2010 = 100*perc_white_2010, 
         turnout_13 = 100*turnout_13) %>% 
  lm(100*turnout_diff_oc1 ~ turnout_13 + 
                        popw_median_age_2010 + popw_median_inc_2010_1k + perc_white_2010, data = .)

mod1b <- SEA_elections_odd %>% 
  mutate(popw_median_inc_2010_1k = popw_median_inc_2010/1000,
         perc_white_2010 = 100*perc_white_2010, 
         turnout_13 = 100*turnout_13) %>% 
  lm(100*turnout_diff_oc1 ~ walk_15_oc1 + turnout_13 + 
                        popw_median_age_2010 + popw_median_inc_2010_1k + perc_white_2010, data = .)

mod1c <- SEA_elections_odd %>% 
  mutate(popw_median_inc_2010_1k = popw_median_inc_2010/1000, 
         perc_white_2010 = 100*perc_white_2010, 
         turnout_13 = 100*turnout_13) %>% 
  lm(100*turnout_diff_oc1 ~ walk_15_oc1_type1 + walk_15_oc1_type2 + turnout_13 + 
                        popw_median_age_2010 + popw_median_inc_2010_1k + perc_white_2010, data = .)

# stargazer(mod1a, mod1b, mod1c, title="Regression Results",
#           dep.var.labels=c("Turnout change"),
#           column.labels = c("Model 1a", "Model 1b", "Model 1c"))

mod2a <- SEA_elections_odd %>%
  mutate(popw_median_inc_2010_1k = popw_median_inc_2010/1000, 
         perc_white_2010 = 100*perc_white_2010, 
         turnout_15 = 100*turnout_15) %>% 
  lm(100*turnout_diff_oc2 ~ turnout_15 + 
                        popw_median_age_2010 + popw_median_inc_2010_1k + perc_white_2010 + 
                        council_dist1 + council_dist2 + council_dist3 + council_dist4 + 
                        council_dist5 + council_dist6, data = .)

mod2b <- SEA_elections_odd %>%
  mutate(popw_median_inc_2010_1k = popw_median_inc_2010/1000, 
         perc_white_2010 = 100*perc_white_2010, 
         turnout_15 = 100*turnout_15) %>% 
  lm(100*turnout_diff_oc2 ~ walk_15_oc2 + turnout_15 + 
                        popw_median_age_2010 + popw_median_inc_2010_1k + perc_white_2010 + 
                        council_dist1 + council_dist2 + council_dist3 + council_dist4 + 
                        council_dist5 + council_dist6, data = .)

mod2c <- SEA_elections_odd %>% 
  mutate(popw_median_inc_2010_1k = popw_median_inc_2010/1000, 
         perc_white_2010 = 100*perc_white_2010, 
         turnout_15 = 100*turnout_15) %>% 
  lm(100*turnout_diff_oc2 ~ walk_15_oc2_type1 + walk_15_oc2_type2 + turnout_15 + 
                        popw_median_age_2010 + popw_median_inc_2010_1k + perc_white_2010 + 
                        council_dist1 + council_dist2 + council_dist3 + council_dist4 + 
                        council_dist5 + council_dist6, data = .)

# stargazer(mod1a, mod1b, mod1c, title="Regression Results",
#           dep.var.labels=c("Turnout change"),
#           column.labels = c("Model 2a", "Model 2b", "Model 2c"))

mod3a <- SEA_elections_even %>%  
  mutate(popw_median_inc_2010_1k = popw_median_inc_2010/1000, 
         perc_white_2010 = 100*perc_white_2010, 
         turnout_14 = 100*turnout_14) %>% 
  lm(100*turnout_diff_ec2 ~ turnout_14 + 
                        popw_median_age_2010 + popw_median_inc_2010_1k + perc_white_2010 + 
                        cong_dist7, data = .)

mod3b <- SEA_elections_even %>%   
  mutate(popw_median_inc_2010_1k = popw_median_inc_2010/1000, 
         perc_white_2010 = 100*perc_white_2010, 
         turnout_14 = 100*turnout_14) %>% 
  lm(100*turnout_diff_ec2 ~ walk_15_ec2 + turnout_14 + 
                        popw_median_age_2010 + popw_median_inc_2010_1k + perc_white_2010 + 
                        cong_dist7, data = .)

mod3c <- SEA_elections_even %>%   
  mutate(popw_median_inc_2010_1k = popw_median_inc_2010/1000, 
         perc_white_2010 = 100*perc_white_2010, 
         turnout_14 = 100*turnout_14) %>% 
  lm(100*turnout_diff_ec2 ~ walk_15_ec2_type1 + walk_15_ec2_type2 + turnout_14 + 
                        popw_median_age_2010 + popw_median_inc_2010_1k + perc_white_2010 + 
                        cong_dist7, data = .)

# stargazer(mod1a, mod1b, mod1c, title="Regression Results",
#           dep.var.labels=c("Turnout change"),
#           column.labels = c("Model 3a", "Model 3b", "Model 3c"))

mod4a <- SEA_elections_even %>%  
  mutate(popw_median_inc_2010_1k = popw_median_inc_2010/1000, 
         perc_white_2010 = 100*perc_white_2010, 
         turnout_16 = 100*turnout_16) %>% 
  lm(100*turnout_diff_ec3 ~ turnout_16 + 
                        popw_median_age_2010 + popw_median_inc_2010_1k + perc_white_2010, data = .)

mod4b <- SEA_elections_even %>%   
  mutate(popw_median_inc_2010_1k = popw_median_inc_2010/1000, 
         perc_white_2010 = 100*perc_white_2010, 
         turnout_16 = 100*turnout_16) %>% 
  lm(100*turnout_diff_ec3 ~ walk_15_ec3 + turnout_16 + 
                        popw_median_age_2010 + popw_median_inc_2010_1k + perc_white_2010, data = .)

mod4c <- SEA_elections_even %>%   
  mutate(popw_median_inc_2010_1k = popw_median_inc_2010/1000, 
         perc_white_2010 = 100*perc_white_2010, 
         turnout_16 = 100*turnout_16) %>% 
  lm(100*turnout_diff_ec3 ~ walk_15_ec3_type1 + walk_15_ec3_type2 + turnout_16 + 
                        popw_median_age_2010 + popw_median_inc_2010_1k + perc_white_2010, data = .)

# stargazer(mod4a, mod4b, mod4c, title="Regression Results",
#           dep.var.labels=c("Turnout change"),
#           column.labels = c("Model 4a", "Model 4b", "Model 4c"))

```

```{r}
### FIGURES: MAPS ###

sea_fig1 <- SEA_elections_odd %>% st_as_sf() %>% ggplot() + 
  geom_sf(aes(fill = turnout_diff_oc1)) + theme_void() + 
  scale_fill_fermenter(palette = "RdYlGn", direction = 1, n.breaks = 6,
                       labels = c("-0.15" = "-0.15", "0.10" = "", 
                                  "-0.05" = "-0.05", "0.00" = "", 
                                  "0.05" = "0.05")) + 
  labs(fill = expression(paste(Delta, " turnout"))) + 
  theme(plot.background = element_rect(fill = "white", color = NA),
        legend.position = "bottom")

sea_fig2 <- SEA_elections_odd %>% st_as_sf() %>% ggplot() + 
  geom_sf(aes(fill = turnout_diff_oc2)) + theme_void() + 
  scale_fill_fermenter(palette = "RdYlGn", direction = 1, n.breaks = 6,
                       labels = c("0" = "0.00", "0.05" = "", 
                                  "0.1" = "0.10", "0.15" = "", 
                                  "0.2" = "0.20")) + 
  labs(fill = expression(paste(Delta, " turnout"))) + 
  theme(plot.background = element_rect(fill = "white", color = NA),
        legend.position = "bottom")

sea_fig3 <- SEA_elections_odd %>% st_as_sf() %>% ggplot() + 
  geom_sf(fill = "aliceblue") + theme_void() + 
  geom_sf(data = st_as_sf(spTransform(as_Spatial((SEA_walksheds %>%
                      select(walk_15) %>% 
                      st_as_sf() %>% 
                      st_make_valid() %>% 
                      summarize(walk_15 = st_union(walk_15)))$walk_15) %>% 
                    crop(., extent(st_bbox(SEA_boundary))), 
                    CRS(paste0("+proj=longlat +datum=WGS84 +no_defs", 
                               "+ellps=WGS84 +towgs84=0,0,0")))) %>% 
            mutate(type = "15-min.\nwalkshed"), 
          aes(fill = type), alpha = 0.75) + 
  scale_fill_manual(values = "red", name = "") + 
  theme(plot.background = element_rect(fill = "white", color = NA),
        legend.position = "bottom",
        legend.box.margin = margin(0, 0, 10, 0))

# ggsave("figures/sea/sea_fig1.png", sea_fig1, width = 3, height = 5, dpi = 200)

```

```{r}
### FIGURES: HISTOGRAMS ###

h1 <- SEA_elections_odd %>% 
  ggplot(aes(x = turnout_diff_oc1)) + geom_histogram(fill = "blue") + theme_minimal() + 
  labs(x = NULL, y = NULL) + 
  theme(plot.background = element_rect(fill = "white", color = NA))

h2 <- SEA_elections_odd %>% 
  ggplot(aes(x = walk_15_oc1)) + geom_histogram(fill = "blue") + theme_minimal() + 
  labs(x = NULL, y = NULL) + 
  theme(plot.background = element_rect(fill = "white", color = NA))

h3 <- SEA_elections_odd %>% 
  ggplot(aes(x = turnout_13)) + geom_histogram(fill = "blue") + theme_minimal() + 
  labs(x = NULL, y = NULL) + 
  theme(plot.background = element_rect(fill = "white", color = NA))

h4 <- SEA_elections_odd %>% 
  ggplot(aes(x = perc_white_2010)) + geom_histogram(fill = "blue") + theme_minimal() + 
  labs(x = NULL, y = NULL) + 
  theme(plot.background = element_rect(fill = "white", color = NA))

h5 <- SEA_elections_odd %>% 
  ggplot(aes(x = popw_median_age_2010)) + geom_histogram(fill = "blue") + theme_minimal() + 
  labs(x = NULL, y = NULL) + 
  theme(plot.background = element_rect(fill = "white", color = NA))

h6 <- SEA_elections_odd %>% 
  ggplot(aes(x = popw_median_inc_2010)) + geom_histogram(fill = "blue") + theme_minimal() + 
  labs(x = NULL, y = NULL) + 
  theme(plot.background = element_rect(fill = "white", color = NA))

h7 <- SEA_elections_odd %>% 
  ggplot(aes(x = council_dist1)) + geom_histogram(fill = "blue") + theme_minimal() + 
  labs(x = NULL, y = NULL) + 
  theme(plot.background = element_rect(fill = "white", color = NA))

# ggsave("figures/sea/hist/sea_h7.png", h7, width = 4, height = 3, dpi = 100)

```


```{r}


```














